import faresData from '@modules/trips/data/fares.json';
import * as SearchCtrl from './SearchController';

describe('extractMinFareDeals', () => {
  xit('should extract min data', () => {
    expect(SearchCtrl.extractMinFareDeals(faresData.deals)).toEqual({
      Amsterdam_Brussels: {
        arrival: 'Brussels',
        cost: 40,
        departure: 'Amsterdam',
        reference: 'BAB0545',
      },
      Amsterdam_London: {
        arrival: 'London',
        cost: 20,
        departure: 'Amsterdam',
        reference: 'BAL0545',
      },
      Amsterdam_Warsaw: {
        arrival: 'Warsaw',
        cost: 30,
        departure: 'Amsterdam',
        reference: 'BAW0515',
      },
      Athens_Budapest: {
        arrival: 'Budapest',
        cost: 20,
        departure: 'Athens',
        reference: 'BAB0500',
      },
      Athens_Istanbul: {
        arrival: 'Istanbul',
        cost: 30,
        departure: 'Athens',
        reference: 'BAI0530',
      },
      Athens_Rome: {
        arrival: 'Rome',
        cost: 40,
        departure: 'Athens',
        reference: 'BAR0600',
      },
      Brussels_Amsterdam: {
        arrival: 'Amsterdam',
        cost: 20,
        departure: 'Brussels',
        reference: 'BBA0515',
      },
      Brussels_Geneva: {
        arrival: 'Geneva',
        cost: 40,
        departure: 'Brussels',
        reference: 'BBG0715',
      },
      Brussels_Paris: {
        arrival: 'Paris',
        cost: 40,
        departure: 'Brussels',
        reference: 'BBP0545',
      },
      Brussels_Prague: {
        arrival: 'Prague',
        cost: 20,
        departure: 'Brussels',
        reference: 'BBP0545',
      },
      Budapest_Athens: {
        arrival: 'Athens',
        cost: 20,
        departure: 'Budapest',
        reference: 'BBA0745',
      },
      Budapest_Geneva: {
        arrival: 'Geneva',
        cost: 20,
        departure: 'Budapest',
        reference: 'BBG0500',
      },
      Budapest_Kiev: {
        arrival: 'Kiev',
        cost: 30,
        departure: 'Budapest',
        reference: 'BBK0515',
      },
      Budapest_Prague: {
        arrival: 'Prague',
        cost: 40,
        departure: 'Budapest',
        reference: 'BBP0615',
      },
      Geneva_Brussels: {
        arrival: 'Brussels',
        cost: 40,
        departure: 'Geneva',
        reference: 'BGB0515',
      },
      Geneva_Budapest: {
        arrival: 'Budapest',
        cost: 40,
        departure: 'Geneva',
        reference: 'BGB0530',
      },
      Geneva_Madrid: {
        arrival: 'Madrid',
        cost: 40,
        departure: 'Geneva',
        reference: 'BGM0645',
      },
      Geneva_Rome: {
        arrival: 'Rome',
        cost: 30,
        departure: 'Geneva',
        reference: 'BGR0630',
      },
      Istanbul_Athens: {
        arrival: 'Athens',
        cost: 20,
        departure: 'Istanbul',
        reference: 'BIA0515',
      },
      Istanbul_Kiev: {
        arrival: 'Kiev',
        cost: 30,
        departure: 'Istanbul',
        reference: 'BIK0530',
      },
      Kiev_Budapest: {
        arrival: 'Budapest',
        cost: 20,
        departure: 'Kiev',
        reference: 'BKB0600',
      },
      Kiev_Istanbul: {
        arrival: 'Istanbul',
        cost: 20,
        departure: 'Kiev',
        reference: 'BKI0600',
      },
      Kiev_Moscow: {
        arrival: 'Moscow',
        cost: 40,
        departure: 'Kiev',
        reference: 'BKM0500',
      },
      Lisbon_Madrid: {
        arrival: 'Madrid',
        cost: 40,
        departure: 'Lisbon',
        reference: 'BLM0745',
      },
      Lisbon_Rome: {
        arrival: 'Rome',
        cost: 30,
        departure: 'Lisbon',
        reference: 'BLR0730',
      },
      London_Amsterdam: {
        arrival: 'Amsterdam',
        cost: 30,
        departure: 'London',
        reference: 'BLA0745',
      },
      London_Paris: {
        arrival: 'Paris',
        cost: 20,
        departure: 'London',
        reference: 'BLP0530',
      },
      Madrid_Geneva: {
        arrival: 'Geneva',
        cost: 20,
        departure: 'Madrid',
        reference: 'BMG0730',
      },
      Madrid_Lisbon: {
        arrival: 'Lisbon',
        cost: 30,
        departure: 'Madrid',
        reference: 'BML0500',
      },
      Madrid_Paris: {
        arrival: 'Paris',
        cost: 20,
        departure: 'Madrid',
        reference: 'BMP0530',
      },
      Moscow_Kiev: {
        arrival: 'Kiev',
        cost: 20,
        departure: 'Moscow',
        reference: 'BMK0700',
      },
      Moscow_Prague: {
        arrival: 'Prague',
        cost: 30,
        departure: 'Moscow',
        reference: 'BMP0500',
      },
      Moscow_Stockholm: {
        arrival: 'Stockholm',
        cost: 30,
        departure: 'Moscow',
        reference: 'BMS0600',
      },
      Paris_Brussels: {
        arrival: 'Brussels',
        cost: 30,
        departure: 'Paris',
        reference: 'BPB0630',
      },
      Paris_London: {
        arrival: 'London',
        cost: 20,
        departure: 'Paris',
        reference: 'BPL0615',
      },
      Paris_Madrid: {
        arrival: 'Madrid',
        cost: 30,
        departure: 'Paris',
        reference: 'BPM0645',
      },
      Prague_Brussels: {
        arrival: 'Brussels',
        cost: 30,
        departure: 'Prague',
        reference: 'BPB0515',
      },
      Prague_Budapest: {
        arrival: 'Budapest',
        cost: 30,
        departure: 'Prague',
        reference: 'BPB0700',
      },
      Prague_Moscow: {
        arrival: 'Moscow',
        cost: 30,
        departure: 'Prague',
        reference: 'BPM0500',
      },
      Prague_Warsaw: {
        arrival: 'Warsaw',
        cost: 30,
        departure: 'Prague',
        reference: 'BPW0630',
      },
      Rome_Athens: {
        arrival: 'Athens',
        cost: 40,
        departure: 'Rome',
        reference: 'BRA0745',
      },
      Rome_Geneva: {
        arrival: 'Geneva',
        cost: 20,
        departure: 'Rome',
        reference: 'BRG0700',
      },
      Rome_Lisbon: {
        arrival: 'Lisbon',
        cost: 20,
        departure: 'Rome',
        reference: 'BRL0530',
      },
      Stockholm_Moscow: {
        arrival: 'Moscow',
        cost: 30,
        departure: 'Stockholm',
        reference: 'BSM0530',
      },
      Stockholm_Warsaw: {
        arrival: 'Warsaw',
        cost: 40,
        departure: 'Stockholm',
        reference: 'BSW0545',
      },
      Warsaw_Amsterdam: {
        arrival: 'Amsterdam',
        cost: 40,
        departure: 'Warsaw',
        reference: 'BWA0545',
      },
      Warsaw_Prague: {
        arrival: 'Prague',
        cost: 40,
        departure: 'Warsaw',
        reference: 'BWP0615',
      },
      Warsaw_Stockholm: {
        arrival: 'Stockholm',
        cost: 20,
        departure: 'Warsaw',
        reference: 'BWS0515',
      },
    });
  });
});

describe('makeGraphFromMinFares', () => {
  xit('should return graph', () => {
    expect(
      SearchCtrl.makeGraphFromMinFares({
        Amsterdam_Brussels: {
          arrival: 'Brussels',
          cost: 40,
          departure: 'Amsterdam',
          reference: 'BAB0545',
        },
        Amsterdam_London: {
          arrival: 'London',
          cost: 20,
          departure: 'Amsterdam',
          reference: 'BAL0545',
        },
        Amsterdam_Warsaw: {
          arrival: 'Warsaw',
          cost: 30,
          departure: 'Amsterdam',
          reference: 'BAW0515',
        },
        Athens_Budapest: {
          arrival: 'Budapest',
          cost: 20,
          departure: 'Athens',
          reference: 'BAB0500',
        },
        Athens_Istanbul: {
          arrival: 'Istanbul',
          cost: 30,
          departure: 'Athens',
          reference: 'BAI0530',
        },
        Athens_Rome: {
          arrival: 'Rome',
          cost: 40,
          departure: 'Athens',
          reference: 'BAR0600',
        },
        Brussels_Amsterdam: {
          arrival: 'Amsterdam',
          cost: 20,
          departure: 'Brussels',
          reference: 'BBA0515',
        },
        Brussels_Geneva: {
          arrival: 'Geneva',
          cost: 40,
          departure: 'Brussels',
          reference: 'BBG0715',
        },
        Brussels_Paris: {
          arrival: 'Paris',
          cost: 40,
          departure: 'Brussels',
          reference: 'BBP0545',
        },
        Brussels_Prague: {
          arrival: 'Prague',
          cost: 20,
          departure: 'Brussels',
          reference: 'BBP0545',
        },
        Budapest_Athens: {
          arrival: 'Athens',
          cost: 20,
          departure: 'Budapest',
          reference: 'BBA0745',
        },
        Budapest_Geneva: {
          arrival: 'Geneva',
          cost: 20,
          departure: 'Budapest',
          reference: 'BBG0500',
        },
        Budapest_Kiev: {
          arrival: 'Kiev',
          cost: 30,
          departure: 'Budapest',
          reference: 'BBK0515',
        },
        Budapest_Prague: {
          arrival: 'Prague',
          cost: 40,
          departure: 'Budapest',
          reference: 'BBP0615',
        },
        Geneva_Brussels: {
          arrival: 'Brussels',
          cost: 40,
          departure: 'Geneva',
          reference: 'BGB0515',
        },
        Geneva_Budapest: {
          arrival: 'Budapest',
          cost: 40,
          departure: 'Geneva',
          reference: 'BGB0530',
        },
        Geneva_Madrid: {
          arrival: 'Madrid',
          cost: 40,
          departure: 'Geneva',
          reference: 'BGM0645',
        },
        Geneva_Rome: {
          arrival: 'Rome',
          cost: 30,
          departure: 'Geneva',
          reference: 'BGR0630',
        },
        Istanbul_Athens: {
          arrival: 'Athens',
          cost: 20,
          departure: 'Istanbul',
          reference: 'BIA0515',
        },
        Istanbul_Kiev: {
          arrival: 'Kiev',
          cost: 30,
          departure: 'Istanbul',
          reference: 'BIK0530',
        },
        Kiev_Budapest: {
          arrival: 'Budapest',
          cost: 20,
          departure: 'Kiev',
          reference: 'BKB0600',
        },
        Kiev_Istanbul: {
          arrival: 'Istanbul',
          cost: 20,
          departure: 'Kiev',
          reference: 'BKI0600',
        },
        Kiev_Moscow: {
          arrival: 'Moscow',
          cost: 40,
          departure: 'Kiev',
          reference: 'BKM0500',
        },
        Lisbon_Madrid: {
          arrival: 'Madrid',
          cost: 40,
          departure: 'Lisbon',
          reference: 'BLM0745',
        },
        Lisbon_Rome: {
          arrival: 'Rome',
          cost: 30,
          departure: 'Lisbon',
          reference: 'BLR0730',
        },
        London_Amsterdam: {
          arrival: 'Amsterdam',
          cost: 30,
          departure: 'London',
          reference: 'BLA0745',
        },
        London_Paris: {
          arrival: 'Paris',
          cost: 20,
          departure: 'London',
          reference: 'BLP0530',
        },
        Madrid_Geneva: {
          arrival: 'Geneva',
          cost: 20,
          departure: 'Madrid',
          reference: 'BMG0730',
        },
        Madrid_Lisbon: {
          arrival: 'Lisbon',
          cost: 30,
          departure: 'Madrid',
          reference: 'BML0500',
        },
        Madrid_Paris: {
          arrival: 'Paris',
          cost: 20,
          departure: 'Madrid',
          reference: 'BMP0530',
        },
        Moscow_Kiev: {
          arrival: 'Kiev',
          cost: 20,
          departure: 'Moscow',
          reference: 'BMK0700',
        },
        Moscow_Prague: {
          arrival: 'Prague',
          cost: 30,
          departure: 'Moscow',
          reference: 'BMP0500',
        },
        Moscow_Stockholm: {
          arrival: 'Stockholm',
          cost: 30,
          departure: 'Moscow',
          reference: 'BMS0600',
        },
        Paris_Brussels: {
          arrival: 'Brussels',
          cost: 30,
          departure: 'Paris',
          reference: 'BPB0630',
        },
        Paris_London: {
          arrival: 'London',
          cost: 20,
          departure: 'Paris',
          reference: 'BPL0615',
        },
        Paris_Madrid: {
          arrival: 'Madrid',
          cost: 30,
          departure: 'Paris',
          reference: 'BPM0645',
        },
        Prague_Brussels: {
          arrival: 'Brussels',
          cost: 30,
          departure: 'Prague',
          reference: 'BPB0515',
        },
        Prague_Budapest: {
          arrival: 'Budapest',
          cost: 30,
          departure: 'Prague',
          reference: 'BPB0700',
        },
        Prague_Moscow: {
          arrival: 'Moscow',
          cost: 30,
          departure: 'Prague',
          reference: 'BPM0500',
        },
        Prague_Warsaw: {
          arrival: 'Warsaw',
          cost: 30,
          departure: 'Prague',
          reference: 'BPW0630',
        },
        Rome_Athens: {
          arrival: 'Athens',
          cost: 40,
          departure: 'Rome',
          reference: 'BRA0745',
        },
        Rome_Geneva: {
          arrival: 'Geneva',
          cost: 20,
          departure: 'Rome',
          reference: 'BRG0700',
        },
        Rome_Lisbon: {
          arrival: 'Lisbon',
          cost: 20,
          departure: 'Rome',
          reference: 'BRL0530',
        },
        Stockholm_Moscow: {
          arrival: 'Moscow',
          cost: 30,
          departure: 'Stockholm',
          reference: 'BSM0530',
        },
        Stockholm_Warsaw: {
          arrival: 'Warsaw',
          cost: 40,
          departure: 'Stockholm',
          reference: 'BSW0545',
        },
        Warsaw_Amsterdam: {
          arrival: 'Amsterdam',
          cost: 40,
          departure: 'Warsaw',
          reference: 'BWA0545',
        },
        Warsaw_Prague: {
          arrival: 'Prague',
          cost: 40,
          departure: 'Warsaw',
          reference: 'BWP0615',
        },
        Warsaw_Stockholm: {
          arrival: 'Stockholm',
          cost: 20,
          departure: 'Warsaw',
          reference: 'BWS0515',
        },
      }),
    ).toEqual({});
  });
});

describe('normalizeDeals', () => {
  it('should normalize deals array', () => {
    expect(SearchCtrl.normalizeDeals(faresData.deals)).toEqual({
      TLA0500: {
        transport: 'train',
        departure: 'London',
        arrival: 'Amsterdam',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TLA0500',
      },
      BLA0745: {
        transport: 'bus',
        departure: 'London',
        arrival: 'Amsterdam',
        duration: {
          h: '07',
          m: '45',
        },
        cost: 40,
        discount: 25,
        reference: 'BLA0745',
      },
      CLA0445: {
        transport: 'car',
        departure: 'London',
        arrival: 'Amsterdam',
        duration: {
          h: '04',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CLA0445',
      },
      TLP0430: {
        transport: 'train',
        departure: 'London',
        arrival: 'Paris',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 160,
        discount: 0,
        reference: 'TLP0430',
      },
      BLP0530: {
        transport: 'bus',
        departure: 'London',
        arrival: 'Paris',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 40,
        discount: 50,
        reference: 'BLP0530',
      },
      CLP0415: {
        transport: 'car',
        departure: 'London',
        arrival: 'Paris',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CLP0415',
      },
      TAW0515: {
        transport: 'train',
        departure: 'Amsterdam',
        arrival: 'Warsaw',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 160,
        discount: 25,
        reference: 'TAW0515',
      },
      BAW0515: {
        transport: 'bus',
        departure: 'Amsterdam',
        arrival: 'Warsaw',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 40,
        discount: 25,
        reference: 'BAW0515',
      },
      CAW0445: {
        transport: 'car',
        departure: 'Amsterdam',
        arrival: 'Warsaw',
        duration: {
          h: '04',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CAW0445',
      },
      TAB0530: {
        transport: 'train',
        departure: 'Athens',
        arrival: 'Budapest',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 160,
        discount: 0,
        reference: 'TAB0530',
      },
      BAB0545: {
        transport: 'bus',
        departure: 'Amsterdam',
        arrival: 'Brussels',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 40,
        discount: 0,
        reference: 'BAB0545',
      },
      CAB0430: {
        transport: 'car',
        departure: 'Amsterdam',
        arrival: 'Brussels',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CAB0430',
      },
      TAL0415: {
        transport: 'train',
        departure: 'Amsterdam',
        arrival: 'London',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 160,
        discount: 25,
        reference: 'TAL0415',
      },
      BAL0545: {
        transport: 'bus',
        departure: 'Amsterdam',
        arrival: 'London',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 40,
        discount: 50,
        reference: 'BAL0545',
      },
      CAL0400: {
        transport: 'car',
        departure: 'Amsterdam',
        arrival: 'London',
        duration: {
          h: '04',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CAL0400',
      },
      TWS0515: {
        transport: 'train',
        departure: 'Warsaw',
        arrival: 'Stockholm',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 160,
        discount: 25,
        reference: 'TWS0515',
      },
      BWS0515: {
        transport: 'bus',
        departure: 'Warsaw',
        arrival: 'Stockholm',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 40,
        discount: 50,
        reference: 'BWS0515',
      },
      CWS0515: {
        transport: 'car',
        departure: 'Warsaw',
        arrival: 'Stockholm',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CWS0515',
      },
      TWP0300: {
        transport: 'train',
        departure: 'Warsaw',
        arrival: 'Prague',
        duration: {
          h: '03',
          m: '00',
        },
        cost: 160,
        discount: 25,
        reference: 'TWP0300',
      },
      BWP0615: {
        transport: 'bus',
        departure: 'Warsaw',
        arrival: 'Prague',
        duration: {
          h: '06',
          m: '15',
        },
        cost: 40,
        discount: 0,
        reference: 'BWP0615',
      },
      CWP0445: {
        transport: 'car',
        departure: 'Warsaw',
        arrival: 'Prague',
        duration: {
          h: '04',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CWP0445',
      },
      TWA0530: {
        transport: 'train',
        departure: 'Warsaw',
        arrival: 'Amsterdam',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 160,
        discount: 0,
        reference: 'TWA0530',
      },
      BWA0545: {
        transport: 'bus',
        departure: 'Warsaw',
        arrival: 'Amsterdam',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 40,
        discount: 0,
        reference: 'BWA0545',
      },
      CWA0415: {
        transport: 'car',
        departure: 'Warsaw',
        arrival: 'Amsterdam',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CWA0415',
      },
      TSM0430: {
        transport: 'train',
        departure: 'Stockholm',
        arrival: 'Moscow',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 160,
        discount: 25,
        reference: 'TSM0430',
      },
      BSM0530: {
        transport: 'bus',
        departure: 'Stockholm',
        arrival: 'Moscow',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 40,
        discount: 25,
        reference: 'BSM0530',
      },
      CSM0400: {
        transport: 'car',
        departure: 'Stockholm',
        arrival: 'Moscow',
        duration: {
          h: '04',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CSM0400',
      },
      TSW0500: {
        transport: 'train',
        departure: 'Stockholm',
        arrival: 'Warsaw',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 25,
        reference: 'TSW0500',
      },
      BSW0545: {
        transport: 'bus',
        departure: 'Stockholm',
        arrival: 'Warsaw',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 40,
        discount: 0,
        reference: 'BSW0545',
      },
      CSW0545: {
        transport: 'car',
        departure: 'Stockholm',
        arrival: 'Warsaw',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CSW0545',
      },
      TPL0315: {
        transport: 'train',
        departure: 'Paris',
        arrival: 'London',
        duration: {
          h: '03',
          m: '15',
        },
        cost: 160,
        discount: 25,
        reference: 'TPL0315',
      },
      BPL0615: {
        transport: 'bus',
        departure: 'Paris',
        arrival: 'London',
        duration: {
          h: '06',
          m: '15',
        },
        cost: 40,
        discount: 50,
        reference: 'BPL0615',
      },
      CPL0545: {
        transport: 'car',
        departure: 'Paris',
        arrival: 'London',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CPL0545',
      },
      TPB0530: {
        transport: 'train',
        departure: 'Paris',
        arrival: 'Brussels',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 160,
        discount: 25,
        reference: 'TPB0530',
      },
      BPB0630: {
        transport: 'bus',
        departure: 'Paris',
        arrival: 'Brussels',
        duration: {
          h: '06',
          m: '30',
        },
        cost: 40,
        discount: 25,
        reference: 'BPB0630',
      },
      CPB0545: {
        transport: 'car',
        departure: 'Paris',
        arrival: 'Brussels',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CPB0545',
      },
      TPM0315: {
        transport: 'train',
        departure: 'Paris',
        arrival: 'Madrid',
        duration: {
          h: '03',
          m: '15',
        },
        cost: 160,
        discount: 0,
        reference: 'TPM0315',
      },
      BPM0645: {
        transport: 'bus',
        departure: 'Paris',
        arrival: 'Madrid',
        duration: {
          h: '06',
          m: '45',
        },
        cost: 40,
        discount: 25,
        reference: 'BPM0645',
      },
      CPM0545: {
        transport: 'car',
        departure: 'Paris',
        arrival: 'Madrid',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CPM0545',
      },
      TBA0515: {
        transport: 'train',
        departure: 'Brussels',
        arrival: 'Amsterdam',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 160,
        discount: 0,
        reference: 'TBA0515',
      },
      BBA0515: {
        transport: 'bus',
        departure: 'Brussels',
        arrival: 'Amsterdam',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 40,
        discount: 50,
        reference: 'BBA0515',
      },
      CBA0430: {
        transport: 'car',
        departure: 'Brussels',
        arrival: 'Amsterdam',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CBA0430',
      },
      TBP0300: {
        transport: 'train',
        departure: 'Brussels',
        arrival: 'Prague',
        duration: {
          h: '03',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TBP0300',
      },
      BBP0545: {
        transport: 'bus',
        departure: 'Brussels',
        arrival: 'Paris',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 40,
        discount: 0,
        reference: 'BBP0545',
      },
      CBP0430: {
        transport: 'car',
        departure: 'Brussels',
        arrival: 'Prague',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CBP0430',
      },
      TBG0445: {
        transport: 'train',
        departure: 'Brussels',
        arrival: 'Geneva',
        duration: {
          h: '04',
          m: '45',
        },
        cost: 160,
        discount: 0,
        reference: 'TBG0445',
      },
      BBG0715: {
        transport: 'bus',
        departure: 'Brussels',
        arrival: 'Geneva',
        duration: {
          h: '07',
          m: '15',
        },
        cost: 40,
        discount: 0,
        reference: 'BBG0715',
      },
      CBG0515: {
        transport: 'car',
        departure: 'Brussels',
        arrival: 'Geneva',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CBG0515',
      },
      TBP0400: {
        transport: 'train',
        departure: 'Brussels',
        arrival: 'Paris',
        duration: {
          h: '04',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TBP0400',
      },
      CBP0415: {
        transport: 'car',
        departure: 'Brussels',
        arrival: 'Paris',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CBP0415',
      },
      TPW0430: {
        transport: 'train',
        departure: 'Prague',
        arrival: 'Warsaw',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 160,
        discount: 50,
        reference: 'TPW0430',
      },
      BPW0630: {
        transport: 'bus',
        departure: 'Prague',
        arrival: 'Warsaw',
        duration: {
          h: '06',
          m: '30',
        },
        cost: 40,
        discount: 25,
        reference: 'BPW0630',
      },
      CPW0430: {
        transport: 'car',
        departure: 'Prague',
        arrival: 'Warsaw',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CPW0430',
      },
      TPM0415: {
        transport: 'train',
        departure: 'Prague',
        arrival: 'Moscow',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 160,
        discount: 0,
        reference: 'TPM0415',
      },
      BPM0500: {
        transport: 'bus',
        departure: 'Prague',
        arrival: 'Moscow',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 40,
        discount: 25,
        reference: 'BPM0500',
      },
      CPM0515: {
        transport: 'car',
        departure: 'Prague',
        arrival: 'Moscow',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CPM0515',
      },
      TPB0400: {
        transport: 'train',
        departure: 'Prague',
        arrival: 'Budapest',
        duration: {
          h: '04',
          m: '00',
        },
        cost: 160,
        discount: 25,
        reference: 'TPB0400',
      },
      BPB0700: {
        transport: 'bus',
        departure: 'Prague',
        arrival: 'Budapest',
        duration: {
          h: '07',
          m: '00',
        },
        cost: 40,
        discount: 25,
        reference: 'BPB0700',
      },
      CPB0430: {
        transport: 'car',
        departure: 'Prague',
        arrival: 'Budapest',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CPB0430',
      },
      TPB0515: {
        transport: 'train',
        departure: 'Prague',
        arrival: 'Brussels',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 160,
        discount: 0,
        reference: 'TPB0515',
      },
      BPB0515: {
        transport: 'bus',
        departure: 'Prague',
        arrival: 'Brussels',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 40,
        discount: 25,
        reference: 'BPB0515',
      },
      CPB0530: {
        transport: 'car',
        departure: 'Prague',
        arrival: 'Brussels',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CPB0530',
      },
      TMS0345: {
        transport: 'train',
        departure: 'Moscow',
        arrival: 'Stockholm',
        duration: {
          h: '03',
          m: '45',
        },
        cost: 160,
        discount: 0,
        reference: 'TMS0345',
      },
      BMS0600: {
        transport: 'bus',
        departure: 'Moscow',
        arrival: 'Stockholm',
        duration: {
          h: '06',
          m: '00',
        },
        cost: 40,
        discount: 25,
        reference: 'BMS0600',
      },
      CMS0430: {
        transport: 'car',
        departure: 'Moscow',
        arrival: 'Stockholm',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CMS0430',
      },
      TMK0515: {
        transport: 'train',
        departure: 'Moscow',
        arrival: 'Kiev',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 160,
        discount: 50,
        reference: 'TMK0515',
      },
      BMK0700: {
        transport: 'bus',
        departure: 'Moscow',
        arrival: 'Kiev',
        duration: {
          h: '07',
          m: '00',
        },
        cost: 40,
        discount: 50,
        reference: 'BMK0700',
      },
      CMK0415: {
        transport: 'car',
        departure: 'Moscow',
        arrival: 'Kiev',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CMK0415',
      },
      TMP0330: {
        transport: 'train',
        departure: 'Moscow',
        arrival: 'Prague',
        duration: {
          h: '03',
          m: '30',
        },
        cost: 160,
        discount: 0,
        reference: 'TMP0330',
      },
      BMP0500: {
        transport: 'bus',
        departure: 'Moscow',
        arrival: 'Prague',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 40,
        discount: 25,
        reference: 'BMP0500',
      },
      CMP0530: {
        transport: 'car',
        departure: 'Moscow',
        arrival: 'Prague',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CMP0530',
      },
      TMP0500: {
        transport: 'train',
        departure: 'Madrid',
        arrival: 'Paris',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 50,
        reference: 'TMP0500',
      },
      BMP0530: {
        transport: 'bus',
        departure: 'Madrid',
        arrival: 'Paris',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 40,
        discount: 50,
        reference: 'BMP0530',
      },
      CMP0545: {
        transport: 'car',
        departure: 'Madrid',
        arrival: 'Paris',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CMP0545',
      },
      TMG0500: {
        transport: 'train',
        departure: 'Madrid',
        arrival: 'Geneva',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 25,
        reference: 'TMG0500',
      },
      BMG0730: {
        transport: 'bus',
        departure: 'Madrid',
        arrival: 'Geneva',
        duration: {
          h: '07',
          m: '30',
        },
        cost: 40,
        discount: 50,
        reference: 'BMG0730',
      },
      CMG0415: {
        transport: 'car',
        departure: 'Madrid',
        arrival: 'Geneva',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CMG0415',
      },
      TML0400: {
        transport: 'train',
        departure: 'Madrid',
        arrival: 'Lisbon',
        duration: {
          h: '04',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TML0400',
      },
      BML0500: {
        transport: 'bus',
        departure: 'Madrid',
        arrival: 'Lisbon',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 40,
        discount: 25,
        reference: 'BML0500',
      },
      CML0500: {
        transport: 'car',
        departure: 'Madrid',
        arrival: 'Lisbon',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CML0500',
      },
      TGB0300: {
        transport: 'train',
        departure: 'Geneva',
        arrival: 'Brussels',
        duration: {
          h: '03',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TGB0300',
      },
      BGB0515: {
        transport: 'bus',
        departure: 'Geneva',
        arrival: 'Brussels',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 40,
        discount: 0,
        reference: 'BGB0515',
      },
      CGB0500: {
        transport: 'car',
        departure: 'Geneva',
        arrival: 'Budapest',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CGB0500',
      },
      TGB0445: {
        transport: 'train',
        departure: 'Geneva',
        arrival: 'Budapest',
        duration: {
          h: '04',
          m: '45',
        },
        cost: 160,
        discount: 0,
        reference: 'TGB0445',
      },
      BGB0530: {
        transport: 'bus',
        departure: 'Geneva',
        arrival: 'Budapest',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 40,
        discount: 0,
        reference: 'BGB0530',
      },
      TGR0330: {
        transport: 'train',
        departure: 'Geneva',
        arrival: 'Rome',
        duration: {
          h: '03',
          m: '30',
        },
        cost: 160,
        discount: 0,
        reference: 'TGR0330',
      },
      BGR0630: {
        transport: 'bus',
        departure: 'Geneva',
        arrival: 'Rome',
        duration: {
          h: '06',
          m: '30',
        },
        cost: 40,
        discount: 25,
        reference: 'BGR0630',
      },
      CGR0545: {
        transport: 'car',
        departure: 'Geneva',
        arrival: 'Rome',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CGR0545',
      },
      TGM0500: {
        transport: 'train',
        departure: 'Geneva',
        arrival: 'Madrid',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 25,
        reference: 'TGM0500',
      },
      BGM0645: {
        transport: 'bus',
        departure: 'Geneva',
        arrival: 'Madrid',
        duration: {
          h: '06',
          m: '45',
        },
        cost: 40,
        discount: 0,
        reference: 'BGM0645',
      },
      CGM0545: {
        transport: 'car',
        departure: 'Geneva',
        arrival: 'Madrid',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CGM0545',
      },
      TBP0345: {
        transport: 'train',
        departure: 'Budapest',
        arrival: 'Prague',
        duration: {
          h: '03',
          m: '45',
        },
        cost: 160,
        discount: 0,
        reference: 'TBP0345',
      },
      BBP0615: {
        transport: 'bus',
        departure: 'Budapest',
        arrival: 'Prague',
        duration: {
          h: '06',
          m: '15',
        },
        cost: 40,
        discount: 0,
        reference: 'BBP0615',
      },
      CBP0530: {
        transport: 'car',
        departure: 'Budapest',
        arrival: 'Prague',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CBP0530',
      },
      TBK0515: {
        transport: 'train',
        departure: 'Budapest',
        arrival: 'Kiev',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 160,
        discount: 50,
        reference: 'TBK0515',
      },
      BBK0515: {
        transport: 'bus',
        departure: 'Budapest',
        arrival: 'Kiev',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 40,
        discount: 25,
        reference: 'BBK0515',
      },
      CBK0515: {
        transport: 'car',
        departure: 'Budapest',
        arrival: 'Kiev',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CBK0515',
      },
      TBA0330: {
        transport: 'train',
        departure: 'Budapest',
        arrival: 'Athens',
        duration: {
          h: '03',
          m: '30',
        },
        cost: 160,
        discount: 0,
        reference: 'TBA0330',
      },
      BBA0745: {
        transport: 'bus',
        departure: 'Budapest',
        arrival: 'Athens',
        duration: {
          h: '07',
          m: '45',
        },
        cost: 40,
        discount: 50,
        reference: 'BBA0745',
      },
      CBA0530: {
        transport: 'car',
        departure: 'Budapest',
        arrival: 'Athens',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CBA0530',
      },
      TBG0300: {
        transport: 'train',
        departure: 'Budapest',
        arrival: 'Geneva',
        duration: {
          h: '03',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TBG0300',
      },
      BBG0500: {
        transport: 'bus',
        departure: 'Budapest',
        arrival: 'Geneva',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 40,
        discount: 50,
        reference: 'BBG0500',
      },
      CBG0415: {
        transport: 'car',
        departure: 'Budapest',
        arrival: 'Geneva',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CBG0415',
      },
      TKM0500: {
        transport: 'train',
        departure: 'Kiev',
        arrival: 'Moscow',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TKM0500',
      },
      BKM0500: {
        transport: 'bus',
        departure: 'Kiev',
        arrival: 'Moscow',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 40,
        discount: 0,
        reference: 'BKM0500',
      },
      CKM0500: {
        transport: 'car',
        departure: 'Kiev',
        arrival: 'Moscow',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CKM0500',
      },
      TKI0415: {
        transport: 'train',
        departure: 'Kiev',
        arrival: 'Istanbul',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 160,
        discount: 25,
        reference: 'TKI0415',
      },
      BKI0600: {
        transport: 'bus',
        departure: 'Kiev',
        arrival: 'Istanbul',
        duration: {
          h: '06',
          m: '00',
        },
        cost: 40,
        discount: 50,
        reference: 'BKI0600',
      },
      CKI0415: {
        transport: 'car',
        departure: 'Kiev',
        arrival: 'Istanbul',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CKI0415',
      },
      TKB0500: {
        transport: 'train',
        departure: 'Kiev',
        arrival: 'Budapest',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TKB0500',
      },
      BKB0600: {
        transport: 'bus',
        departure: 'Kiev',
        arrival: 'Budapest',
        duration: {
          h: '06',
          m: '00',
        },
        cost: 40,
        discount: 50,
        reference: 'BKB0600',
      },
      CKB0415: {
        transport: 'car',
        departure: 'Kiev',
        arrival: 'Budapest',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CKB0415',
      },
      TLM0500: {
        transport: 'train',
        departure: 'Lisbon',
        arrival: 'Madrid',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TLM0500',
      },
      BLM0745: {
        transport: 'bus',
        departure: 'Lisbon',
        arrival: 'Madrid',
        duration: {
          h: '07',
          m: '45',
        },
        cost: 40,
        discount: 0,
        reference: 'BLM0745',
      },
      CLM0430: {
        transport: 'car',
        departure: 'Lisbon',
        arrival: 'Madrid',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CLM0430',
      },
      TLR0530: {
        transport: 'train',
        departure: 'Lisbon',
        arrival: 'Rome',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 160,
        discount: 50,
        reference: 'TLR0530',
      },
      BLR0730: {
        transport: 'bus',
        departure: 'Lisbon',
        arrival: 'Rome',
        duration: {
          h: '07',
          m: '30',
        },
        cost: 40,
        discount: 25,
        reference: 'BLR0730',
      },
      CLR0500: {
        transport: 'car',
        departure: 'Lisbon',
        arrival: 'Rome',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CLR0500',
      },
      TRG0500: {
        transport: 'train',
        departure: 'Rome',
        arrival: 'Geneva',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 50,
        reference: 'TRG0500',
      },
      BRG0700: {
        transport: 'bus',
        departure: 'Rome',
        arrival: 'Geneva',
        duration: {
          h: '07',
          m: '00',
        },
        cost: 40,
        discount: 50,
        reference: 'BRG0700',
      },
      CRG0430: {
        transport: 'car',
        departure: 'Rome',
        arrival: 'Geneva',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CRG0430',
      },
      TRA0500: {
        transport: 'train',
        departure: 'Rome',
        arrival: 'Athens',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 160,
        discount: 0,
        reference: 'TRA0500',
      },
      BRA0745: {
        transport: 'bus',
        departure: 'Rome',
        arrival: 'Athens',
        duration: {
          h: '07',
          m: '45',
        },
        cost: 40,
        discount: 0,
        reference: 'BRA0745',
      },
      CRA0430: {
        transport: 'car',
        departure: 'Rome',
        arrival: 'Athens',
        duration: {
          h: '04',
          m: '30',
        },
        cost: 120,
        discount: 0,
        reference: 'CRA0430',
      },
      TRL0415: {
        transport: 'train',
        departure: 'Rome',
        arrival: 'Lisbon',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 160,
        discount: 25,
        reference: 'TRL0415',
      },
      BRL0530: {
        transport: 'bus',
        departure: 'Rome',
        arrival: 'Lisbon',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 40,
        discount: 50,
        reference: 'BRL0530',
      },
      CRL0500: {
        transport: 'car',
        departure: 'Rome',
        arrival: 'Lisbon',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CRL0500',
      },
      BAB0500: {
        transport: 'bus',
        departure: 'Athens',
        arrival: 'Budapest',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 40,
        discount: 50,
        reference: 'BAB0500',
      },
      CAB0445: {
        transport: 'car',
        departure: 'Athens',
        arrival: 'Budapest',
        duration: {
          h: '04',
          m: '45',
        },
        cost: 120,
        discount: 0,
        reference: 'CAB0445',
      },
      TAI0545: {
        transport: 'train',
        departure: 'Athens',
        arrival: 'Istanbul',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 160,
        discount: 25,
        reference: 'TAI0545',
      },
      BAI0530: {
        transport: 'bus',
        departure: 'Athens',
        arrival: 'Istanbul',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 40,
        discount: 25,
        reference: 'BAI0530',
      },
      CAI0515: {
        transport: 'car',
        departure: 'Athens',
        arrival: 'Istanbul',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CAI0515',
      },
      TAR0545: {
        transport: 'train',
        departure: 'Athens',
        arrival: 'Rome',
        duration: {
          h: '05',
          m: '45',
        },
        cost: 160,
        discount: 0,
        reference: 'TAR0545',
      },
      BAR0600: {
        transport: 'bus',
        departure: 'Athens',
        arrival: 'Rome',
        duration: {
          h: '06',
          m: '00',
        },
        cost: 40,
        discount: 0,
        reference: 'BAR0600',
      },
      CAR0415: {
        transport: 'car',
        departure: 'Athens',
        arrival: 'Rome',
        duration: {
          h: '04',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CAR0415',
      },
      TIK0530: {
        transport: 'train',
        departure: 'Istanbul',
        arrival: 'Kiev',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 160,
        discount: 25,
        reference: 'TIK0530',
      },
      BIK0530: {
        transport: 'bus',
        departure: 'Istanbul',
        arrival: 'Kiev',
        duration: {
          h: '05',
          m: '30',
        },
        cost: 40,
        discount: 25,
        reference: 'BIK0530',
      },
      CIK0500: {
        transport: 'car',
        departure: 'Istanbul',
        arrival: 'Kiev',
        duration: {
          h: '05',
          m: '00',
        },
        cost: 120,
        discount: 0,
        reference: 'CIK0500',
      },
      TIA0330: {
        transport: 'train',
        departure: 'Istanbul',
        arrival: 'Athens',
        duration: {
          h: '03',
          m: '30',
        },
        cost: 160,
        discount: 25,
        reference: 'TIA0330',
      },
      BIA0515: {
        transport: 'bus',
        departure: 'Istanbul',
        arrival: 'Athens',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 40,
        discount: 50,
        reference: 'BIA0515',
      },
      CIA0515: {
        transport: 'car',
        departure: 'Istanbul',
        arrival: 'Athens',
        duration: {
          h: '05',
          m: '15',
        },
        cost: 120,
        discount: 0,
        reference: 'CIA0515',
      },
    });
  });

  it('should return false if not array', () => {
    expect(SearchCtrl.normalizeDeals()).toEqual(false);
  });
});

describe('dealsFilter', () => {
  const normalizedDeals = {
    TLA0500: {
      transport: 'train',
      departure: 'London',
      arrival: 'Amsterdam',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TLA0500',
    },
    BLA0745: {
      transport: 'bus',
      departure: 'London',
      arrival: 'Amsterdam',
      duration: {
        h: '07',
        m: '45',
      },
      cost: 40,
      discount: 25,
      reference: 'BLA0745',
    },
    CLA0445: {
      transport: 'car',
      departure: 'London',
      arrival: 'Amsterdam',
      duration: {
        h: '04',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CLA0445',
    },
    TLP0430: {
      transport: 'train',
      departure: 'London',
      arrival: 'Paris',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 160,
      discount: 0,
      reference: 'TLP0430',
    },
    BLP0530: {
      transport: 'bus',
      departure: 'London',
      arrival: 'Paris',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 40,
      discount: 50,
      reference: 'BLP0530',
    },
    CLP0415: {
      transport: 'car',
      departure: 'London',
      arrival: 'Paris',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CLP0415',
    },
    TAW0515: {
      transport: 'train',
      departure: 'Amsterdam',
      arrival: 'Warsaw',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 160,
      discount: 25,
      reference: 'TAW0515',
    },
    BAW0515: {
      transport: 'bus',
      departure: 'Amsterdam',
      arrival: 'Warsaw',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 40,
      discount: 25,
      reference: 'BAW0515',
    },
    CAW0445: {
      transport: 'car',
      departure: 'Amsterdam',
      arrival: 'Warsaw',
      duration: {
        h: '04',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CAW0445',
    },
    TAB0530: {
      transport: 'train',
      departure: 'Athens',
      arrival: 'Budapest',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 160,
      discount: 0,
      reference: 'TAB0530',
    },
    BAB0545: {
      transport: 'bus',
      departure: 'Amsterdam',
      arrival: 'Brussels',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 40,
      discount: 0,
      reference: 'BAB0545',
    },
    CAB0430: {
      transport: 'car',
      departure: 'Amsterdam',
      arrival: 'Brussels',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CAB0430',
    },
    TAL0415: {
      transport: 'train',
      departure: 'Amsterdam',
      arrival: 'London',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 160,
      discount: 25,
      reference: 'TAL0415',
    },
    BAL0545: {
      transport: 'bus',
      departure: 'Amsterdam',
      arrival: 'London',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 40,
      discount: 50,
      reference: 'BAL0545',
    },
    CAL0400: {
      transport: 'car',
      departure: 'Amsterdam',
      arrival: 'London',
      duration: {
        h: '04',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CAL0400',
    },
    TWS0515: {
      transport: 'train',
      departure: 'Warsaw',
      arrival: 'Stockholm',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 160,
      discount: 25,
      reference: 'TWS0515',
    },
    BWS0515: {
      transport: 'bus',
      departure: 'Warsaw',
      arrival: 'Stockholm',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 40,
      discount: 50,
      reference: 'BWS0515',
    },
    CWS0515: {
      transport: 'car',
      departure: 'Warsaw',
      arrival: 'Stockholm',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CWS0515',
    },
    TWP0300: {
      transport: 'train',
      departure: 'Warsaw',
      arrival: 'Prague',
      duration: {
        h: '03',
        m: '00',
      },
      cost: 160,
      discount: 25,
      reference: 'TWP0300',
    },
    BWP0615: {
      transport: 'bus',
      departure: 'Warsaw',
      arrival: 'Prague',
      duration: {
        h: '06',
        m: '15',
      },
      cost: 40,
      discount: 0,
      reference: 'BWP0615',
    },
    CWP0445: {
      transport: 'car',
      departure: 'Warsaw',
      arrival: 'Prague',
      duration: {
        h: '04',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CWP0445',
    },
    TWA0530: {
      transport: 'train',
      departure: 'Warsaw',
      arrival: 'Amsterdam',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 160,
      discount: 0,
      reference: 'TWA0530',
    },
    BWA0545: {
      transport: 'bus',
      departure: 'Warsaw',
      arrival: 'Amsterdam',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 40,
      discount: 0,
      reference: 'BWA0545',
    },
    CWA0415: {
      transport: 'car',
      departure: 'Warsaw',
      arrival: 'Amsterdam',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CWA0415',
    },
    TSM0430: {
      transport: 'train',
      departure: 'Stockholm',
      arrival: 'Moscow',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 160,
      discount: 25,
      reference: 'TSM0430',
    },
    BSM0530: {
      transport: 'bus',
      departure: 'Stockholm',
      arrival: 'Moscow',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 40,
      discount: 25,
      reference: 'BSM0530',
    },
    CSM0400: {
      transport: 'car',
      departure: 'Stockholm',
      arrival: 'Moscow',
      duration: {
        h: '04',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CSM0400',
    },
    TSW0500: {
      transport: 'train',
      departure: 'Stockholm',
      arrival: 'Warsaw',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 25,
      reference: 'TSW0500',
    },
    BSW0545: {
      transport: 'bus',
      departure: 'Stockholm',
      arrival: 'Warsaw',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 40,
      discount: 0,
      reference: 'BSW0545',
    },
    CSW0545: {
      transport: 'car',
      departure: 'Stockholm',
      arrival: 'Warsaw',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CSW0545',
    },
    TPL0315: {
      transport: 'train',
      departure: 'Paris',
      arrival: 'London',
      duration: {
        h: '03',
        m: '15',
      },
      cost: 160,
      discount: 25,
      reference: 'TPL0315',
    },
    BPL0615: {
      transport: 'bus',
      departure: 'Paris',
      arrival: 'London',
      duration: {
        h: '06',
        m: '15',
      },
      cost: 40,
      discount: 50,
      reference: 'BPL0615',
    },
    CPL0545: {
      transport: 'car',
      departure: 'Paris',
      arrival: 'London',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CPL0545',
    },
    TPB0530: {
      transport: 'train',
      departure: 'Paris',
      arrival: 'Brussels',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 160,
      discount: 25,
      reference: 'TPB0530',
    },
    BPB0630: {
      transport: 'bus',
      departure: 'Paris',
      arrival: 'Brussels',
      duration: {
        h: '06',
        m: '30',
      },
      cost: 40,
      discount: 25,
      reference: 'BPB0630',
    },
    CPB0545: {
      transport: 'car',
      departure: 'Paris',
      arrival: 'Brussels',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CPB0545',
    },
    TPM0315: {
      transport: 'train',
      departure: 'Paris',
      arrival: 'Madrid',
      duration: {
        h: '03',
        m: '15',
      },
      cost: 160,
      discount: 0,
      reference: 'TPM0315',
    },
    BPM0645: {
      transport: 'bus',
      departure: 'Paris',
      arrival: 'Madrid',
      duration: {
        h: '06',
        m: '45',
      },
      cost: 40,
      discount: 25,
      reference: 'BPM0645',
    },
    CPM0545: {
      transport: 'car',
      departure: 'Paris',
      arrival: 'Madrid',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CPM0545',
    },
    TBA0515: {
      transport: 'train',
      departure: 'Brussels',
      arrival: 'Amsterdam',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 160,
      discount: 0,
      reference: 'TBA0515',
    },
    BBA0515: {
      transport: 'bus',
      departure: 'Brussels',
      arrival: 'Amsterdam',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 40,
      discount: 50,
      reference: 'BBA0515',
    },
    CBA0430: {
      transport: 'car',
      departure: 'Brussels',
      arrival: 'Amsterdam',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CBA0430',
    },
    TBP0300: {
      transport: 'train',
      departure: 'Brussels',
      arrival: 'Prague',
      duration: {
        h: '03',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TBP0300',
    },
    BBP0545: {
      transport: 'bus',
      departure: 'Brussels',
      arrival: 'Paris',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 40,
      discount: 0,
      reference: 'BBP0545',
    },
    CBP0430: {
      transport: 'car',
      departure: 'Brussels',
      arrival: 'Prague',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CBP0430',
    },
    TBG0445: {
      transport: 'train',
      departure: 'Brussels',
      arrival: 'Geneva',
      duration: {
        h: '04',
        m: '45',
      },
      cost: 160,
      discount: 0,
      reference: 'TBG0445',
    },
    BBG0715: {
      transport: 'bus',
      departure: 'Brussels',
      arrival: 'Geneva',
      duration: {
        h: '07',
        m: '15',
      },
      cost: 40,
      discount: 0,
      reference: 'BBG0715',
    },
    CBG0515: {
      transport: 'car',
      departure: 'Brussels',
      arrival: 'Geneva',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CBG0515',
    },
    TBP0400: {
      transport: 'train',
      departure: 'Brussels',
      arrival: 'Paris',
      duration: {
        h: '04',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TBP0400',
    },
    CBP0415: {
      transport: 'car',
      departure: 'Brussels',
      arrival: 'Paris',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CBP0415',
    },
    TPW0430: {
      transport: 'train',
      departure: 'Prague',
      arrival: 'Warsaw',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 160,
      discount: 50,
      reference: 'TPW0430',
    },
    BPW0630: {
      transport: 'bus',
      departure: 'Prague',
      arrival: 'Warsaw',
      duration: {
        h: '06',
        m: '30',
      },
      cost: 40,
      discount: 25,
      reference: 'BPW0630',
    },
    CPW0430: {
      transport: 'car',
      departure: 'Prague',
      arrival: 'Warsaw',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CPW0430',
    },
    TPM0415: {
      transport: 'train',
      departure: 'Prague',
      arrival: 'Moscow',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 160,
      discount: 0,
      reference: 'TPM0415',
    },
    BPM0500: {
      transport: 'bus',
      departure: 'Prague',
      arrival: 'Moscow',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 40,
      discount: 25,
      reference: 'BPM0500',
    },
    CPM0515: {
      transport: 'car',
      departure: 'Prague',
      arrival: 'Moscow',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CPM0515',
    },
    TPB0400: {
      transport: 'train',
      departure: 'Prague',
      arrival: 'Budapest',
      duration: {
        h: '04',
        m: '00',
      },
      cost: 160,
      discount: 25,
      reference: 'TPB0400',
    },
    BPB0700: {
      transport: 'bus',
      departure: 'Prague',
      arrival: 'Budapest',
      duration: {
        h: '07',
        m: '00',
      },
      cost: 40,
      discount: 25,
      reference: 'BPB0700',
    },
    CPB0430: {
      transport: 'car',
      departure: 'Prague',
      arrival: 'Budapest',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CPB0430',
    },
    TPB0515: {
      transport: 'train',
      departure: 'Prague',
      arrival: 'Brussels',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 160,
      discount: 0,
      reference: 'TPB0515',
    },
    BPB0515: {
      transport: 'bus',
      departure: 'Prague',
      arrival: 'Brussels',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 40,
      discount: 25,
      reference: 'BPB0515',
    },
    CPB0530: {
      transport: 'car',
      departure: 'Prague',
      arrival: 'Brussels',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CPB0530',
    },
    TMS0345: {
      transport: 'train',
      departure: 'Moscow',
      arrival: 'Stockholm',
      duration: {
        h: '03',
        m: '45',
      },
      cost: 160,
      discount: 0,
      reference: 'TMS0345',
    },
    BMS0600: {
      transport: 'bus',
      departure: 'Moscow',
      arrival: 'Stockholm',
      duration: {
        h: '06',
        m: '00',
      },
      cost: 40,
      discount: 25,
      reference: 'BMS0600',
    },
    CMS0430: {
      transport: 'car',
      departure: 'Moscow',
      arrival: 'Stockholm',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CMS0430',
    },
    TMK0515: {
      transport: 'train',
      departure: 'Moscow',
      arrival: 'Kiev',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 160,
      discount: 50,
      reference: 'TMK0515',
    },
    BMK0700: {
      transport: 'bus',
      departure: 'Moscow',
      arrival: 'Kiev',
      duration: {
        h: '07',
        m: '00',
      },
      cost: 40,
      discount: 50,
      reference: 'BMK0700',
    },
    CMK0415: {
      transport: 'car',
      departure: 'Moscow',
      arrival: 'Kiev',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CMK0415',
    },
    TMP0330: {
      transport: 'train',
      departure: 'Moscow',
      arrival: 'Prague',
      duration: {
        h: '03',
        m: '30',
      },
      cost: 160,
      discount: 0,
      reference: 'TMP0330',
    },
    BMP0500: {
      transport: 'bus',
      departure: 'Moscow',
      arrival: 'Prague',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 40,
      discount: 25,
      reference: 'BMP0500',
    },
    CMP0530: {
      transport: 'car',
      departure: 'Moscow',
      arrival: 'Prague',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CMP0530',
    },
    TMP0500: {
      transport: 'train',
      departure: 'Madrid',
      arrival: 'Paris',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 50,
      reference: 'TMP0500',
    },
    BMP0530: {
      transport: 'bus',
      departure: 'Madrid',
      arrival: 'Paris',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 40,
      discount: 50,
      reference: 'BMP0530',
    },
    CMP0545: {
      transport: 'car',
      departure: 'Madrid',
      arrival: 'Paris',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CMP0545',
    },
    TMG0500: {
      transport: 'train',
      departure: 'Madrid',
      arrival: 'Geneva',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 25,
      reference: 'TMG0500',
    },
    BMG0730: {
      transport: 'bus',
      departure: 'Madrid',
      arrival: 'Geneva',
      duration: {
        h: '07',
        m: '30',
      },
      cost: 40,
      discount: 50,
      reference: 'BMG0730',
    },
    CMG0415: {
      transport: 'car',
      departure: 'Madrid',
      arrival: 'Geneva',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CMG0415',
    },
    TML0400: {
      transport: 'train',
      departure: 'Madrid',
      arrival: 'Lisbon',
      duration: {
        h: '04',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TML0400',
    },
    BML0500: {
      transport: 'bus',
      departure: 'Madrid',
      arrival: 'Lisbon',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 40,
      discount: 25,
      reference: 'BML0500',
    },
    CML0500: {
      transport: 'car',
      departure: 'Madrid',
      arrival: 'Lisbon',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CML0500',
    },
    TGB0300: {
      transport: 'train',
      departure: 'Geneva',
      arrival: 'Brussels',
      duration: {
        h: '03',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TGB0300',
    },
    BGB0515: {
      transport: 'bus',
      departure: 'Geneva',
      arrival: 'Brussels',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 40,
      discount: 0,
      reference: 'BGB0515',
    },
    CGB0500: {
      transport: 'car',
      departure: 'Geneva',
      arrival: 'Budapest',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CGB0500',
    },
    TGB0445: {
      transport: 'train',
      departure: 'Geneva',
      arrival: 'Budapest',
      duration: {
        h: '04',
        m: '45',
      },
      cost: 160,
      discount: 0,
      reference: 'TGB0445',
    },
    BGB0530: {
      transport: 'bus',
      departure: 'Geneva',
      arrival: 'Budapest',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 40,
      discount: 0,
      reference: 'BGB0530',
    },
    TGR0330: {
      transport: 'train',
      departure: 'Geneva',
      arrival: 'Rome',
      duration: {
        h: '03',
        m: '30',
      },
      cost: 160,
      discount: 0,
      reference: 'TGR0330',
    },
    BGR0630: {
      transport: 'bus',
      departure: 'Geneva',
      arrival: 'Rome',
      duration: {
        h: '06',
        m: '30',
      },
      cost: 40,
      discount: 25,
      reference: 'BGR0630',
    },
    CGR0545: {
      transport: 'car',
      departure: 'Geneva',
      arrival: 'Rome',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CGR0545',
    },
    TGM0500: {
      transport: 'train',
      departure: 'Geneva',
      arrival: 'Madrid',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 25,
      reference: 'TGM0500',
    },
    BGM0645: {
      transport: 'bus',
      departure: 'Geneva',
      arrival: 'Madrid',
      duration: {
        h: '06',
        m: '45',
      },
      cost: 40,
      discount: 0,
      reference: 'BGM0645',
    },
    CGM0545: {
      transport: 'car',
      departure: 'Geneva',
      arrival: 'Madrid',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CGM0545',
    },
    TBP0345: {
      transport: 'train',
      departure: 'Budapest',
      arrival: 'Prague',
      duration: {
        h: '03',
        m: '45',
      },
      cost: 160,
      discount: 0,
      reference: 'TBP0345',
    },
    BBP0615: {
      transport: 'bus',
      departure: 'Budapest',
      arrival: 'Prague',
      duration: {
        h: '06',
        m: '15',
      },
      cost: 40,
      discount: 0,
      reference: 'BBP0615',
    },
    CBP0530: {
      transport: 'car',
      departure: 'Budapest',
      arrival: 'Prague',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CBP0530',
    },
    TBK0515: {
      transport: 'train',
      departure: 'Budapest',
      arrival: 'Kiev',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 160,
      discount: 50,
      reference: 'TBK0515',
    },
    BBK0515: {
      transport: 'bus',
      departure: 'Budapest',
      arrival: 'Kiev',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 40,
      discount: 25,
      reference: 'BBK0515',
    },
    CBK0515: {
      transport: 'car',
      departure: 'Budapest',
      arrival: 'Kiev',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CBK0515',
    },
    TBA0330: {
      transport: 'train',
      departure: 'Budapest',
      arrival: 'Athens',
      duration: {
        h: '03',
        m: '30',
      },
      cost: 160,
      discount: 0,
      reference: 'TBA0330',
    },
    BBA0745: {
      transport: 'bus',
      departure: 'Budapest',
      arrival: 'Athens',
      duration: {
        h: '07',
        m: '45',
      },
      cost: 40,
      discount: 50,
      reference: 'BBA0745',
    },
    CBA0530: {
      transport: 'car',
      departure: 'Budapest',
      arrival: 'Athens',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CBA0530',
    },
    TBG0300: {
      transport: 'train',
      departure: 'Budapest',
      arrival: 'Geneva',
      duration: {
        h: '03',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TBG0300',
    },
    BBG0500: {
      transport: 'bus',
      departure: 'Budapest',
      arrival: 'Geneva',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 40,
      discount: 50,
      reference: 'BBG0500',
    },
    CBG0415: {
      transport: 'car',
      departure: 'Budapest',
      arrival: 'Geneva',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CBG0415',
    },
    TKM0500: {
      transport: 'train',
      departure: 'Kiev',
      arrival: 'Moscow',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TKM0500',
    },
    BKM0500: {
      transport: 'bus',
      departure: 'Kiev',
      arrival: 'Moscow',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 40,
      discount: 0,
      reference: 'BKM0500',
    },
    CKM0500: {
      transport: 'car',
      departure: 'Kiev',
      arrival: 'Moscow',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CKM0500',
    },
    TKI0415: {
      transport: 'train',
      departure: 'Kiev',
      arrival: 'Istanbul',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 160,
      discount: 25,
      reference: 'TKI0415',
    },
    BKI0600: {
      transport: 'bus',
      departure: 'Kiev',
      arrival: 'Istanbul',
      duration: {
        h: '06',
        m: '00',
      },
      cost: 40,
      discount: 50,
      reference: 'BKI0600',
    },
    CKI0415: {
      transport: 'car',
      departure: 'Kiev',
      arrival: 'Istanbul',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CKI0415',
    },
    TKB0500: {
      transport: 'train',
      departure: 'Kiev',
      arrival: 'Budapest',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TKB0500',
    },
    BKB0600: {
      transport: 'bus',
      departure: 'Kiev',
      arrival: 'Budapest',
      duration: {
        h: '06',
        m: '00',
      },
      cost: 40,
      discount: 50,
      reference: 'BKB0600',
    },
    CKB0415: {
      transport: 'car',
      departure: 'Kiev',
      arrival: 'Budapest',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CKB0415',
    },
    TLM0500: {
      transport: 'train',
      departure: 'Lisbon',
      arrival: 'Madrid',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TLM0500',
    },
    BLM0745: {
      transport: 'bus',
      departure: 'Lisbon',
      arrival: 'Madrid',
      duration: {
        h: '07',
        m: '45',
      },
      cost: 40,
      discount: 0,
      reference: 'BLM0745',
    },
    CLM0430: {
      transport: 'car',
      departure: 'Lisbon',
      arrival: 'Madrid',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CLM0430',
    },
    TLR0530: {
      transport: 'train',
      departure: 'Lisbon',
      arrival: 'Rome',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 160,
      discount: 50,
      reference: 'TLR0530',
    },
    BLR0730: {
      transport: 'bus',
      departure: 'Lisbon',
      arrival: 'Rome',
      duration: {
        h: '07',
        m: '30',
      },
      cost: 40,
      discount: 25,
      reference: 'BLR0730',
    },
    CLR0500: {
      transport: 'car',
      departure: 'Lisbon',
      arrival: 'Rome',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CLR0500',
    },
    TRG0500: {
      transport: 'train',
      departure: 'Rome',
      arrival: 'Geneva',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 50,
      reference: 'TRG0500',
    },
    BRG0700: {
      transport: 'bus',
      departure: 'Rome',
      arrival: 'Geneva',
      duration: {
        h: '07',
        m: '00',
      },
      cost: 40,
      discount: 50,
      reference: 'BRG0700',
    },
    CRG0430: {
      transport: 'car',
      departure: 'Rome',
      arrival: 'Geneva',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CRG0430',
    },
    TRA0500: {
      transport: 'train',
      departure: 'Rome',
      arrival: 'Athens',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 160,
      discount: 0,
      reference: 'TRA0500',
    },
    BRA0745: {
      transport: 'bus',
      departure: 'Rome',
      arrival: 'Athens',
      duration: {
        h: '07',
        m: '45',
      },
      cost: 40,
      discount: 0,
      reference: 'BRA0745',
    },
    CRA0430: {
      transport: 'car',
      departure: 'Rome',
      arrival: 'Athens',
      duration: {
        h: '04',
        m: '30',
      },
      cost: 120,
      discount: 0,
      reference: 'CRA0430',
    },
    TRL0415: {
      transport: 'train',
      departure: 'Rome',
      arrival: 'Lisbon',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 160,
      discount: 25,
      reference: 'TRL0415',
    },
    BRL0530: {
      transport: 'bus',
      departure: 'Rome',
      arrival: 'Lisbon',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 40,
      discount: 50,
      reference: 'BRL0530',
    },
    CRL0500: {
      transport: 'car',
      departure: 'Rome',
      arrival: 'Lisbon',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CRL0500',
    },
    BAB0500: {
      transport: 'bus',
      departure: 'Athens',
      arrival: 'Budapest',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 40,
      discount: 50,
      reference: 'BAB0500',
    },
    CAB0445: {
      transport: 'car',
      departure: 'Athens',
      arrival: 'Budapest',
      duration: {
        h: '04',
        m: '45',
      },
      cost: 120,
      discount: 0,
      reference: 'CAB0445',
    },
    TAI0545: {
      transport: 'train',
      departure: 'Athens',
      arrival: 'Istanbul',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 160,
      discount: 25,
      reference: 'TAI0545',
    },
    BAI0530: {
      transport: 'bus',
      departure: 'Athens',
      arrival: 'Istanbul',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 40,
      discount: 25,
      reference: 'BAI0530',
    },
    CAI0515: {
      transport: 'car',
      departure: 'Athens',
      arrival: 'Istanbul',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CAI0515',
    },
    TAR0545: {
      transport: 'train',
      departure: 'Athens',
      arrival: 'Rome',
      duration: {
        h: '05',
        m: '45',
      },
      cost: 160,
      discount: 0,
      reference: 'TAR0545',
    },
    BAR0600: {
      transport: 'bus',
      departure: 'Athens',
      arrival: 'Rome',
      duration: {
        h: '06',
        m: '00',
      },
      cost: 40,
      discount: 0,
      reference: 'BAR0600',
    },
    CAR0415: {
      transport: 'car',
      departure: 'Athens',
      arrival: 'Rome',
      duration: {
        h: '04',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CAR0415',
    },
    TIK0530: {
      transport: 'train',
      departure: 'Istanbul',
      arrival: 'Kiev',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 160,
      discount: 25,
      reference: 'TIK0530',
    },
    BIK0530: {
      transport: 'bus',
      departure: 'Istanbul',
      arrival: 'Kiev',
      duration: {
        h: '05',
        m: '30',
      },
      cost: 40,
      discount: 25,
      reference: 'BIK0530',
    },
    CIK0500: {
      transport: 'car',
      departure: 'Istanbul',
      arrival: 'Kiev',
      duration: {
        h: '05',
        m: '00',
      },
      cost: 120,
      discount: 0,
      reference: 'CIK0500',
    },
    TIA0330: {
      transport: 'train',
      departure: 'Istanbul',
      arrival: 'Athens',
      duration: {
        h: '03',
        m: '30',
      },
      cost: 160,
      discount: 25,
      reference: 'TIA0330',
    },
    BIA0515: {
      transport: 'bus',
      departure: 'Istanbul',
      arrival: 'Athens',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 40,
      discount: 50,
      reference: 'BIA0515',
    },
    CIA0515: {
      transport: 'car',
      departure: 'Istanbul',
      arrival: 'Athens',
      duration: {
        h: '05',
        m: '15',
      },
      cost: 120,
      discount: 0,
      reference: 'CIA0515',
    },
  };
  it('should filter deals', () => {
    expect(
      SearchCtrl.dealsFilter(['TLA0500', 'BLA0745'], normalizedDeals),
    ).toEqual([]);
  });

  it('should return false if not array', () => {
    expect(SearchCtrl.dealsFilter(undefined)).toEqual(false);
  });
});
